### ISSUE TITLE
Can you share the weights of split-and-rephrase model trained on WikiSplit dataset ? 

### ISSUE THREAD

**Issue by ToddBear** [kasnerz/zeroshot-d2t-pipeline#3]

**Comment by kasnerz** [comment]
Sure! I have added the [link](https://owncloud.cesnet.cz/index.php/s/AJna6AcDvN5AvQo/download) to README. It a seq2seq model, so the usage is the same as for the PC models.

**Comment by ToddBear** [comment]
Thank you for sharing !
